document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id); const els=['testMode','manualMode','modeTitle','testText','typingInput','inputHint','startBtn','finishBtn','resetBtn','timer','wpm','accuracy','words','errors','resultSection','resultWpm','resultAccuracy','resultTime','resultWords','resultErrors','goalResult','resultMessage','statusText','statusDot','duration','category','goal','progressBar','history','bestWpm','bestAccuracy','totalTests','streak','practiceTime','heroBest','heroTests','themeBtn','notesBtn','notesModal','closeNotes','cancelNotes','saveNotes','notesInput','clearHistory','keyboard'].reduce((o,k)=>(o[k]=$(k),o),{});
let mode='test',running=false,startTime=0,elapsed=0,interval=null,sourceText='',notesText=localStorage.getItem('typetrackNotes')||''; let history=JSON.parse(localStorage.getItem('typetrackHistory')||'[]');
const texts={general:'Typing regularly helps students improve their speed, accuracy and confidence. Practice every day and focus on correct finger placement, steady rhythm and fewer mistakes.',computer:'Computers process information using hardware and software. Learning keyboard shortcuts, programming concepts and digital tools can make everyday work faster and more efficient.',iot:'The Internet of Things connects sensors, devices and systems to collect data and automate useful actions. IoT projects often combine microcontrollers, networks and real world sensors.',programming:'Programming is the process of giving clear instructions to a computer. Good code is readable, logical and tested carefully. Small improvements in practice can lead to stronger problem solving skills.'};
function getText(){if(mode==='manual'&&notesText.trim())return notesText.trim(); return texts[els.category.value]||texts.general}
function setText(){sourceText=getText(); if(mode==='manual'&&notesText.trim()){els.testText.style.display='block';els.textHint.textContent='Your saved notes'} else if(mode==='manual'){els.testText.style.display='block';sourceText='Paste your notes using My Notes, then start practice.';els.textHint.textContent='Add your notes first'} else els.textHint.textContent='Test paragraph'; renderText()}
function renderText(){els.testText.innerHTML=[...sourceText].map((c,i)=>`<span data-i="${i}">${c===' '?'&nbsp;':escapeHtml(c)}</span>`).join('')}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function format(sec){sec=Math.max(0,Math.floor(sec));return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function calc(){const typed=els.typingInput.value; const mins=Math.max((Date.now()-startTime)/60000,1/60000); const speed=Math.round((typed.length/5)/mins); let correct=0,errors=0; if(mode==='test'){for(let i=0;i<typed.length;i++){if(typed[i]===sourceText[i])correct++;else errors++} } else {errors=0} const acc=mode==='manual'?'—':Math.round((correct/Math.max(typed.length,1))*100); const wc=typed.trim()?typed.trim().split(/\s+/).length:0; els.wpm.textContent=speed;els.words.textContent=wc;els.errors.textContent=errors;els.accuracy.textContent=acc==='—'?'—':acc+'%'; els.timer.textContent=els.duration.value==='0'?format((Date.now()-startTime)/1000):format(Math.max(0,Number(els.duration.value)-(Date.now()-startTime)/1000)); const pct=sourceText.length?Math.min(100,(typed.length/sourceText.length)*100):0;els.progressBar.style.width=pct+'%'; highlight(typed);return {speed,acc,wc,errors,seconds:(Date.now()-startTime)/1000}}
function highlight(typed){if(mode!=='test')return; [...els.testText.children].forEach((sp,i)=>{sp.className=''; if(i<typed.length)sp.classList.add(typed[i]===sourceText[i]?'correct':'wrong'); else if(i===typed.length)sp.classList.add('current')})}
function start(){if(running)return; if(mode==='manual'&&!notesText.trim()){els.notesModal.classList.add('show');return} reset(false);running=true;startTime=Date.now();els.typingInput.disabled=false;els.typingInput.focus();els.startBtn.disabled=true;els.finishBtn.disabled=false;els.statusText.textContent='Typing...';els.statusDot.classList.add('running');interval=setInterval(()=>{const r=calc(); if(Number(els.duration.value)>0 && (Date.now()-startTime)/1000>=Number(els.duration.value))finish()},100);calc()}
function finish(){if(!running)return;const r=calc();running=false;clearInterval(interval);elapsed=r.seconds;els.typingInput.disabled=true;els.startBtn.disabled=false;els.finishBtn.disabled=true;els.statusText.textContent='Completed';els.statusDot.classList.remove('running');els.resultSection.style.display='block';els.resultWpm.textContent=r.speed+' WPM';els.resultAccuracy.textContent=r.acc==='—'?'—':r.acc+'%';els.resultTime.textContent=format(r.seconds);els.resultWords.textContent=r.wc;els.resultErrors.textContent=r.errors;const goal=Number(els.goal.value)||40;els.goalResult.textContent=r.speed>=goal?'✅ Achieved':'❌ '+goal+' WPM';els.resultMessage.textContent=r.speed>=goal?'Excellent! You beat your daily goal. Keep the streak alive 🔥':'Good practice! Try to beat '+goal+' WPM next time.'; history.unshift({date:new Date().toLocaleString(),mode,category:els.category.value,wpm:r.speed,accuracy:r.acc,seconds:r.seconds,errors:r.errors});history=history.slice(0,20);saveHistory();renderDashboard();els.resultSection.scrollIntoView({behavior:'smooth',block:'center'})}
function reset(full=true){clearInterval(interval);running=false;els.typingInput.value='';els.typingInput.disabled=true;els.startBtn.disabled=false;els.finishBtn.disabled=true;els.statusText.textContent='Ready';els.statusDot.classList.remove('running');els.resultSection.style.display='none';els.wpm.textContent='0';els.words.textContent='0';els.errors.textContent='0';els.accuracy.textContent=mode==='manual'?'—':'100%';els.progressBar.style.width='0%';const d=Number(els.duration.value);els.timer.textContent=d?format(d):'00:00';setText();if(full){} }
function saveHistory(){localStorage.setItem('typetrackHistory',JSON.stringify(history))}
function renderDashboard(){const tests=history.length,best=Math.max(0,...history.map(x=>x.wpm||0)),acc=tests?Math.max(...history.filter(x=>x.accuracy!=='—').map(x=>x.accuracy||0),0):0,total=history.reduce((s,x)=>s+(x.seconds||0),0);els.bestWpm.textContent=best;els.bestAccuracy.textContent=acc+'%';els.totalTests.textContent=tests;els.practiceTime.textContent=Math.floor(total/60)+'m';els.streak.textContent=calcStreak(history)+' days';els.heroBest.textContent=best;els.heroTests.textContent=tests+' test'+(tests===1?'':'s')+' completed';els.history.innerHTML=tests?history.slice(0,8).map(x=>`<div class="history-row"><span>${x.date}</span><b>${x.wpm} WPM</b><b>${x.accuracy==='—'?'—':x.accuracy+'%'}</b><span>${x.errors} errors</span><span class="hide-mobile">${x.mode==='test'?'Test':'Manual'}</span></div>`).join(''):'<div class="empty">No sessions yet. Start your first test! 🚀</div>'}
function calcStreak(h){const days=[...new Set(h.map(x=>new Date(x.date).toDateString()))];let n=0,d=new Date();for(let i=0;i<days.length;i++){if(days.includes(d.toDateString())){n++;d.setDate(d.getDate()-1)}else break}return n}
function buildKeyboard(){const rows=['1234567890-=', 'QWERTYUIOP[]', 'ASDFGHJKL;\'', 'ZXCVBNM,./'];els.keyboard.innerHTML=rows.map(row=>[...row].map(k=>`<div class="key" data-key="${k.toLowerCase()}">${k}</div>`).join('')).join('')+'<div class="key wide" data-key="shift">SHIFT</div><div class="key space" data-key=" ">SPACE</div><div class="key wide" data-key="backspace">⌫</div>'}
function keyHighlight(k){document.querySelectorAll('.key').forEach(x=>x.classList.remove('active'));const q=k==='Backspace'?'backspace':k.toLowerCase();const el=document.querySelector(`.key[data-key="${CSS.escape(q)}"]`);if(el)el.classList.add('active')}
els.testMode.onclick=()=>{if(running)return;mode='test';els.testMode.classList.add('active');els.manualMode.classList.remove('active');els.modeTitle.textContent='Typing Test';els.inputHint.textContent='Type the text shown above';els.typingInput.placeholder='Click Start and type the paragraph...';reset()};els.manualMode.onclick=()=>{if(running)return;mode='manual';els.manualMode.classList.add('active');els.testMode.classList.remove('active');els.modeTitle.textContent='Manual Practice';els.inputHint.textContent='Type from your own notes';els.typingInput.placeholder='Type from your notes...';reset()};els.startBtn.onclick=start;els.finishBtn.onclick=finish;els.resetBtn.onclick=()=>reset();els.duration.onchange=()=>{if(!running)reset()};els.category.onchange=()=>{if(mode==='test'&&!running)reset()};els.typingInput.oninput=()=>{if(running)calc()};els.typingInput.onkeydown=e=>keyHighlight(e.key);document.addEventListener('keyup',e=>{if(['Shift','Backspace',' '].includes(e.key)||e.key.length===1)keyHighlight(e.key)});els.themeBtn.onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('typetrackDark',document.body.classList.contains('dark'));els.themeBtn.textContent=document.body.classList.contains('dark')?'☀️':'🌙'};els.notesBtn.onclick=()=>{els.notesInput.value=notesText;els.notesModal.classList.add('show')};els.closeNotes.onclick=els.cancelNotes.onclick=()=>els.notesModal.classList.remove('show');els.saveNotes.onclick=()=>{notesText=els.notesInput.value.trim();localStorage.setItem('typetrackNotes',notesText);els.notesModal.classList.remove('show');mode='manual';els.manualMode.click()};els.clearHistory.onclick=()=>{if(confirm('Clear all TypeTrack history?')){history=[];saveHistory();renderDashboard()}};els.goal.onchange=()=>localStorage.setItem('typetrackGoal',els.goal.value);
if(localStorage.getItem('typetrackDark')==='true'){document.body.classList.add('dark');els.themeBtn.textContent='☀️'}els.goal.value=localStorage.getItem('typetrackGoal')||40;buildKeyboard();renderDashboard();reset();
});
